### ISSUE TITLE
dangling ref

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#1]
Problem with saving and dangling href:

This was reproduced when after we created a second To/From mapping for PatientLanguage, I attempted to delete just the To and From attributes and the error came up
To move forward, I tried deleting the entire SE, then the syntax node as well. In each case, still got the error. This is bad because now I cannot save any changes, and I don’t know how to fix it.

**Comment by mryanlord** [comment]
I used the node creator to made node and got an “unhandled event loop exception error” while debugging I noticed that I had unselected unbounded and had not put in a max occurs. A better error msg would be tell user need a number occurs or unbounded.

**Comment by mryanlord** [comment]
Making fields for the datatype for Guardian_compute, eclipse logged errors and there was no visable data in the editor, though there did seem to be some recording of data (ie, no icon or name visible, but clicking on the blank space did show a field name

**Comment by mryanlord** [comment]
When you click on an existing element the view in the properies window should default to MDMI general even if the last time you were viewing that element you were in the node creation view

**Comment by mryanlord** [comment]
Using the map editor, the file did not load properly from the java perspective- i had to switch to the MDMI perspective, and then back to the java perspective to get the various syntax and semantic elements to load in the editor; i like the java perspective better because of the top/bottom look to the properties

**Comment by mryanlord** [comment]
screen grabs associated with error msgs available at : https://docs.google.com/document/d/114XBzxEr_H452ycXYGXjCxI5MLLjosbrN3ljROgAsHg/edit

**Comment by swmuir** [comment]
Overtaken by Code
