### ISSUE TITLE
Partners MDMI Map Blows up FHIR Transformation

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#105]
No output in transform from Partners to FHIR. Files attached. 
[PartnersNoNAMESPACE.zip](https://github.com/MDMI/mdmiecore/files/1849469/PartnersNoNAMESPACE.zip)
[PartnersNoNAMESPACE.txt](https://github.com/MDMI/mdmiecore/files/1849475/PartnersNoNAMESPACE.txt)

This is output: 

<?xml version="1.0" encoding="UTF-8"?>
<Bundle/>

This is console message:

[INFO] Execute preProcess 
[INFO] Execute processInboundSourceMessage
[INFO] Execute processInboundTargetMessage
[INFO] Execute processConversions 
[INFO] Execute processOutboundTargetMessage
[INFO] Execute postProcess
[INFO] Done

**Comment by swmuir** [comment]
Fixed
