### ISSUE TITLE
FHIR to CDA and CDA to FHIR Care Plain No Movement

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#109]
Both FHIR and CDA work isometrically with the attached maps and source messages. But neither will move back and forth. 
[FHIRCDAMvmtFail.zip](https://github.com/MDMI/mdmiecore/files/1915773/FHIRCDAMvmtFail.zip)

**Comment by swmuir** [comment]
FHIR to CDA - the fhir example needs to lower case structureDefinition
                <meta>
                    <profile value="http://hl7.org/fhir/us/core/structureDefinition/us-core-careplan"/>
                </meta>
currently we are case sensitive but it seems the fhir resources are not particularly consistent

**Comment by mryanlord** [comment]
resolved: sample needs declaration in proper case
