### ISSUE TITLE
FHIR to CDA CarePlan Datatype Mapping and Record Target 

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#110]
Two problems on the FHIR CarePlan to CDA Care Plan Transformation:

runtime gives error no period to DateTime datatype mapping. This is necessary to get the FHIR CarePlan period over to the CDA Care Plan.

Also, all of the references to resouces that are mapped are moving except for PatientID. I imagine this is related to the difficulty determining when to serialize that element. 
[PeriodDatatypePatientID4.17.zip](https://github.com/MDMI/mdmiecore/files/1919601/PeriodDatatypePatientID4.17.zip)

**Comment by swmuir** [comment]
> runtime gives error no period to DateTime datatype mapping. This is necessary to get the FHIR CarePlan period over to the CDA Care Plan.

Period is similar to effective time  IVL_TS in cda - we should be mapping to ".start" and ".end"  - i do not believe the the transform currently supports this but will add it

**Comment by mryanlord** [comment]
Have been mapping with .start and .end. Let me know wne tranform updated and I'll pull/update. tnx

**Comment by mryanlord** [comment]
OBE
