### ISSUE TITLE
Choice Value not making UML to MDMI Transform

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#113]
GoalObservation.value and goalObservation.priorityPreference.value not appearing in MDMI map despite annotations for value type in UML model. 
Model and map attached. 
[ChoiceValue4.17.zip](https://github.com/MDMI/mdmiecore/files/1920940/ChoiceValue4.17.zip)

**Comment by swmuir** [comment]
I was able to get the transform to work but the extension are case senstive

so
CarePlan.goalsSection.goalObservation.value.CD versus CarePlan.goalsSection.goalObservation.value.cd

and i think we only support 3 now
CarePlan.goalsSection.goalObservation.value.CD
CarePlan.goalsSection.goalObservation.value.PQ
and
CarePlan.goalsSection.goalObservation.value.ST

I dump alot of this into the console which can be overwhelming
First i list all the mappings and there rules

`[qvto:transformation] Map for CarePlan
[qvto:transformation] CarePlan.authenticator  :: DocumentAuthenticatorContainer
[qvto:transformation] CarePlan.authenticator.assignedEntity.addr  :: DocumentAuthenicatorOrganizationBusinessAddress
[qvto:transformation] CarePlan.authenticator.assignedEntity.assignedPerson.name  :: DocumentAuthenticatordPersonName
[qvto:transformation] CarePlan.authenticator.assignedEntity.code  :: DocumentAuthenticatorSpecialtyCode
[qvto:transformation] CarePlan.authenticator.assignedEntity.id  :: DocumentAuthenticatorPersonID
[qvto:transformation] CarePlan.authenticator.assignedEntity.telecom(starts-with(@value, 'tel:'))  :: DocumentAuthenticatorBusinessPhoneContact`

second i list every SEER element mapped

`Map GoalObservationIDCode to CarePlan.goalsSection.goalObservation.code`

lastly there is a list of unused elements 

`[qvto:transformation] NOT USED CulturalObservationValueCode  CarePlan.healthConcernsSection.healthConcernAct.culturalAndReligiousObservation.value.CD
[qvto:transformation] NOT USED ProblemObservationAuthorLegalName  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.authorParticipation.assignedAuthor.assignedPerson.name
[qvto:transformation] NOT USED ProblemObservationAuthorID  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.authorParticipation.assignedAuthor.id
[qvto:transformation] NOT USED ProblemObservationAuthorBusinessPhoneContact  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorContainer  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.priorityPreference.authorParticipation
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorName  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.assignedPerson.name
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorSpecialityCode  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.code
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorID  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.id
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorOrganizationID  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.representedOrganization.id
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorOrganizationName  CarePlan.healthConcernsSection.healthConcernAct.encounterDiagnosis2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.representedOrganization.name
[q
`


if there is a report structure to make this easier - let me know 

sean

**Comment by swmuir** [comment]
looks like just the twp
CD and PQ

**Comment by mryanlord** [comment]
Sean is right re: case sensitive. will now make part of troubleshooting expeience
