### ISSUE TITLE
USCoreCondition UML to MDMI Transform Broken

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#114]
USCode Condition resource in UML model was refactored to facilitate FHIR to CDA transform. But tranform is not working - .mdmi map continues to show numerous mappings for each semantic element, when model was refactored to one SEER element per semantic element. Model and Map attached.
[USCoreConditionUMLtoMDMIbug.zip](https://github.com/MDMI/mdmiecore/files/1921167/USCoreConditionUMLtoMDMIbug.zip)

**Comment by swmuir** [comment]
[fhirUSCoreCondition.mdmi.zip](https://github.com/MDMI/mdmiecore/files/1921584/fhirUSCoreCondition.mdmi.zip)

I can not duplicate, here are my results

There have been some updates to mdmi so try a restart and check for updates
i will push the latest i have

**Comment by mryanlord** [comment]
User error
