### ISSUE TITLE
RI Editor adding related concepts semantic metadata to Business Elements

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#12]
Using the 7/6 version, I launched the RI Editor and  added the Person Entity as a related Concept to Patient. Saved the results to web service.  Closed down the app.

I restarted app and Modified Entity Semantic Metadata for the BE PatientName. I changed the top level from Person to Patient. I added a second level with name Person, property of Name, and propertyQualifier of Common.  I saved the results to the web service and closed the application.

I restarted the application and selected the BE PatientName.  The second level Entity Semantic Element Name field as blank and it should be Person.  The dropdown box also only provided a blank selection.  However the property of Name and the PropertyQualifier of Common did appear correctly. Additionally, in the Concept Tree, the entity/Patient concept did not have the related Concept of Patient.

**Comment by SallyConway** [comment]
Unable to reproduce after re-adding the related concept "Person" to the "Patient"

**Comment by swmuir** [comment]
Over taken by new software
