### ISSUE TITLE
Semantic Mappings Window in MDMI editor Not functional

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#121]
this editor is necessary to create mappings of multiple BE to the same SE as far as I can tell. 

Rules appear in mdmi model as From_ and To_. See screenshot attached for example of difference.

![image](https://user-images.githubusercontent.com/19562254/39331903-c8b2bb68-4973-11e8-86ef-458374f6a03d.png)

**Comment by swmuir** [comment]
Multiple supported now through drop down

**Comment by swmuir** [comment]
OBE
