### ISSUE TITLE
Add FHIR Money Datatype supprt

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#126]
For use with claim cost data elements in eLTSS program

fhir datatype reference: https://www.hl7.org/fhir/datatypes.html#Money

**Comment by swmuir** [comment]
Fixed

**Comment by KenLord** [comment]
Sean / Matt,

Money is a type of Quantity where I beleive the units would be dollars, euros, etc.  Is this what you were thing Sean?

**Comment by swmuir** [comment]
forgot to rename function name in commit - re-ran a build should be there now

**Comment by mryanlord** [comment]
added
