### ISSUE TITLE
CPassignment to Partners Transform MessageGroup.MessageModel Exception

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#127]
Transform fail
DEBUG] Loaded message group MessageGroup
[DEBUG] Loaded message model MessageGroup.ModelName
[ERROR] cant find MessageGroup.MessageModel
org.mdmi.core.MdmiException: Cannot resolve reference model MessageGroup.MessageModel
	at org.mdmi.core.MdmiModelRef.resolve(MdmiModelRef.java:139)
	at org.mdmi.core.MdmiModelRef.getModel(MdmiModelRef.java:102)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:86)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:55)
Exception in thread "main" java.lang.AssertionError: Cannot resolve reference model MessageGroup.MessageModel
	at org.junit.Assert.fail(Assert.java:88)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:68)

**Comment by swmuir** [comment]
The first issue is the initial imports of XML all named the same  for mdmi
the runtime uses the combination of the message group and the model name to be unique
That was the fix i put in the ui asking for it versus default
the existing ones need to be updated current the following have the default model name

Let me know the name(s) we want for them all need a description
BHCPmapping
KensMeta18.mdmi
4: <models xmi:id="_ByJucEchEeiThMQo0hQFeQ" messageModelName="ModelName"> 
LTSSBADMessage.mdmi
4: <models xmi:id="_C2SJ4TaXEeilW9Qg3yK-fg" messageModelName="ModelName"> 
RiversideTestXML3.mdmi
4: <models xmi:id="_NrXU4THoEei095YVrOoXVw" messageModelName="ModelName">

**Comment by swmuir** [comment]
I am not sure this will fix the issue but it is a first step - Sean

**Comment by mryanlord** [comment]
also, tested with name changes, still kickin the same error. d'oh

**Comment by swmuir** [comment]
There is now a CP2 is that the active one ?  Can you post the message you are using - i was not able to duplicate the issue at the moment

**Comment by mryanlord** [comment]
latests mdmi maps in git maps. attached is the run configuration. 
[CPassignmentToPartnersLaunch.zip](https://github.com/MDMI/mdmiecore/files/1974826/CPassignmentToPartnersLaunch.zip)

**Comment by swmuir** [comment]
Launch refers to this file CPassignmentTestMsg.xml does not seem to be in the repository

**Comment by mryanlord** [comment]
shit, missed this. attached
[CPassignmentTestMsg.zip](https://github.com/MDMI/mdmiecore/files/1981593/CPassignmentTestMsg.zip)

**Comment by KenLord** [comment]
I am also getting an error when I locally run a transformation of
Source Map:CPassignment2.mdmi
Source Message: CPassignmentTestMsg.xml
Target Map: PartnersNoNAMESPACE.mdmi

I get the following runtime exception
org.mdmi.core.MdmiException: Cannot resolve reference model BHCP.CPassignment
	at org.mdmi.core.MdmiModelRef.resolve(MdmiModelRef.java:139)
	at org.mdmi.core.MdmiModelRef.getModel(MdmiModelRef.java:102)
	at org.mdmi.core.runtime.RuntimeService.runTransformation(RuntimeService.java:86)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:55)
Exception in thread "main" java.lang.AssertionError: Cannot resolve reference model BHCP.CPassignment
	at org.junit.Assert.fail(Assert.java:88)
	at org.mdmi.core.runtime.RuntimeServiceMain.main(RuntimeServiceMain.java:68)

**Comment by KenLord** [comment]
This is the message that was used in the execution that caused the above error.
I change the fie type to txt from xml because git doesn't take xml.
[CPassignmentTestMsg - Copy.txt](https://github.com/MDMI/mdmiecore/files/1984416/CPassignmentTestMsg.-.Copy.txt)

**Comment by swmuir** [comment]
The issue is the resolver code that loads the maps - apparently it does not like the same group name in different models - as a work around rename one of the message group from BHCP to BHCP2

I will probably not get this fixed until after hl7

**Comment by swmuir** [comment]
IMPORTANT - there are still some of the incorrect datatype maps which prevent information from being transformed - they are name "mapStringTo???" these should be deleted 
This was a bug in the UI which should have been fixed make sure you are on the latest

**Comment by KenLord** [comment]
Sean and Matt,

So it appears there is a work around, is this correct?
Sean, when you mean after HL7, do you mean the Connectathon or after you
return from HL7 which is probably closer to the 21st?

The key event is demo to Charley. We need to able able to show multiple
patient records being transformed from Partners / Cambridge into CP
Assignment. I do not think we can do that yet and need to be able to
demonstrate it asap. This is stopping us from achieving our May corporate
goal / requirement to get revenue from Riverside.

Call if issues.

Ken

Ken

**Comment by mryanlord** [comment]
Sorry Sean, I thought of that and thought it had failed as workaround. I
think I configured improperly. Thanks!

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
I just committed updated maps the will not through the exception - but there are some issues with the mappings - we have patient id mapped in alot of places and missing containment structures 
datatypemaps need to be updated

**Comment by mryanlord** [comment]
Yeah, I've been working on the datatype maps today. I would like to revise
and add some to simplify, but I think there is still another UI bug re:
datatype creation. Just logged it. Thanks for the updates.

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by mryanlord** [comment]
issue resolved. feature of runtime. must have proper message and model names.
