### ISSUE TITLE
Enhancement: Set value of SEER Element 2 based on Semantic Element 1

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#128]
Need to state:
 
If Semantic element 1 is CarePlanManager Name then SEER Element 1 (name) is name 
AND SEER Element 2 (function code) is Care Manager
 
Use Case:
 
The Semantic elements in the BHCP data set from Massachusetts include the role in the field (see above example). In CDA and FHIR, the role is a seperate field from the name. Need to be able to set role based on the Semantic element field.

**Comment by swmuir** [comment]
I would think from the SEER perspective we would have a "CareParticipant" container with name, address, blah, blah, and role -
and in this case the role for the container would have "manager"  if you the map cared it could do something if not drop it into a general bucket - am i missing something ?

**Comment by KenLord** [comment]
Agree with Sean.  There is a container that would include Business Elements such as name, function, address, etc.

**Comment by mryanlord** [comment]
Demonstrated use with Semantic Relationship
