### ISSUE TITLE
Cannot set primitive data type for child field of structured datatype

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#131]
UI for Eclipse environment allows to create a DTC Structured Datatype, and create a child Field, but no way to set primitive datatype (e.g. String) for the field. Shows up as fieldName:NONE as opposed to fieldName:String. 

See screenshot below to demonstrate difference: DTC Structured CodedElement has primitive datatypes associated with fields, DTC Structured DocumentSetType does not. 

![image](https://user-images.githubusercontent.com/19562254/39886694-35dae25c-545e-11e8-9887-ce2e5cdf44bb.png)

**Comment by swmuir** [comment]
This is not a simple trivial updated - work around is to edit text; This should not be a recurring issue but send me the field and the data type and i can make the updated

**Comment by mryanlord** [comment]
Its OK, not expected to be simple trivial updated. Our demo this week
should be good even if limited by this, but wanted to get the issue in. I
assume by "edit text' you mean the sample format?

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
>assume by "edit text' you mean the sample format?
what i meant was you can open the file using a text editor and set the data field type 
so the map will work just adding a field from the map editor does not work

**Comment by swmuir** [comment]
one other work around is to open using basic EMF editors

**Comment by mryanlord** [comment]
OBE
