### ISSUE TITLE
CambridgeMultiplesToCPAssignment2 - Number of instances not the same, source to target data not moving

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#132]
Get this message:

[ERROR] PatientName Number of instances in sources and data are not the same,  4 to 8
[ERROR] DocumentAuthorOrganizationName Number of instances in sources and data are not the same,  4 to 8
[ERROR] PatientPhoneContact Number of instances in sources and data are not the same,  2 to 6
[ERROR] PatientID Number of instances in sources and data are not the same,  4 to 8

Changed CPassignment2 syntax and semantic notes associated with above SEER elements to multiple instances, still get the error and no data moving.

Files (maps, message, launch config) attached. Similar problem with PartnersWorkingtoCPassignment2
[NumberInstancesNotSame5.13.zip](https://github.com/MDMI/mdmiecore/files/1998835/NumberInstancesNotSame5.13.zip)

**Comment by swmuir** [comment]
Error might be more then drastic perhaps warning the issue is meant to catch somethings dropping on the floor for mapped elements based on seer in this case it is saying there was 4 patient names found in the source message and 8 found in the target- perhaps this is fine

**Comment by swmuir** [comment]
i was able to run and get data across
<?xml version="1.0" encoding="UTF-8"?>

<Documents>
    <SendDocuments>
        <ProvideAndRegisterDocumentSet id="456MCOID789 ">
            <Document id="456MCOID789 ">
                <Author>
                    <Person assigningAuthority="" id="456MCOID789 " rawXcn=""/>
                    <Institution/>
                </Author>
                <SourcePatientInfo>
                    <Field value="321-658-9635 "/>
                    <Address city="&lt;Lameham " country=""
                        state="&lt;MA "
                        streetAddress="&lt;45 Center Ln " zip="&lt;12486 "/>
                    <Field value="personemail@mail.com "/>
                    <Field value="123-456-8525 "/>
                    <PatientId assigningAuthority=""
                        id="777Medicaid111 " rawXcn=""/>
                    <Field value="999-999-9999 "/>
                    <Name familyName="Frank " givenName="Bill " middleName="G "/>
                </SourcePatientInfo>
                <SourcePatientId assigningAuthority=""
                    id="777Medicaid111 " rawXcn=""/>
            </Document>
            <Author>
                <Institution/>
                <Person assigningAuthority="" id="456MCOID789 " rawXcn=""/>
            </Author>
        </ProvideAndRegisterDocumentSet>
    </SendDocuments>
    <SendDocuments>
        <ProvideAndRegisterDocumentSet>
            <Document>
                <SourcePatientInfo>
                    <Field value="444-444-4444 "/>
                    <Address city="&lt;Hamham " country=""
                        state="&lt;MA " streetAddress="&lt;55 Mill Ln " zip="&lt;03548 "/>
                    <Field value="333-333-3333 "/>
                    <Field value="personemail@mail.com "/>
                    <Name familyName="Jones " givenName="Tom " middleName="E "/>
                    <PatientId assigningAuthority="" id="5555555 " rawXcn=""/>
                    <Field value="222-222-2222 "/>
                </SourcePatientInfo>
                <Author>
                    <Institution/>
                    <Person assigningAuthority="" id="123MCOID456 " rawXcn=""/>
                </Author>
                <SourcePatientId assigningAuthority="" id="5555555 " rawXcn=""/>
            </Document>
            <Author>
                <Institution/>
                <Person assigningAuthority="" id="123MCOID456 " rawXcn=""/>
            </Author>
        </ProvideAndRegisterDocumentSet>
    </SendDocuments>
</Documents>

**Comment by mryanlord** [comment]
its going the other way I cannot get data across - CambridgeMultiples to CPassignment2.  was going crazy trying to figure out how you got it to work.  Put the trace log in for giggles.
[CambridgeMultiplesToCPassignmentTrace.txt](https://github.com/MDMI/mdmiecore/files/2002079/CambridgeMultiplesToCPassignmentTrace.txt)

**Comment by swmuir** [comment]
We need to clean up any of the mapping issues from the UI not supporting setting node on semantic elements;  Next we need to look into the mappings themselves we have patient id mapped to numerous places and some do not look correct ;  make sure we have containers mapped where needed
From a debugging point of view - its easier to modify the sources down to one element then trace to get an idea of whats going on

**Comment by swmuir** [comment]
We also not have the reverse of a roll up - so is this CambridgeMultiples to CPassignment2 needed for production or is a nice to have

**Comment by mryanlord** [comment]
I will go through the list of things you suggest and give an update when
complete.

**Comment by swmuir** [comment]
> We  also not have the reverse of a roll up 

Okay will look to update the runtime

**Comment by mryanlord** [comment]
OK. I did not see any synstax/semantic node issues in the maps. I added
some containers in the CambridgeMultiples, but still getting same, flawed
output. I also fixed a rollup structure in CPassignment2 (realize this does
not fix incoming rollup).

I did find what seems to be a parent/child error in CPassignment2 in the
trace. Threre is child nesting here, but there should not be. Also below
that is error linking values to container nodes, don't know if the two are
connected.

 "name" : "Record_Update_Date",
    "children" : [ {
      "name" : "ACO_MCO_SL",
      "children" : [ ]
    }, {
      "name" : "Record_Status",
      "children" : [ {
        "name" : "ACO_MCO_PID",
        "children" : [ ]
      }, {
        "name" : "Member_Date_of_Birth",
        "children" : [ ]
      }, {
        "name" : "ACO_MCO_Name",
        "children" : [ ]
      }, {
        "name" : "ACO_MCO_SL",
        "children" : [ ]
      }, {
        "name" : "Medicaid_ID",
        "children" : [ ]
      }, {
        "name" : "Member_Sex",
        "children" : [ {
          "name" : "Medicaid_ID",
          "children" : [ ]
        }, {
          "name" : "Phone_Number_Cell",
          "type" : "java.lang.String",
          "value" : "(781)255-9999^PRN^PH^",
          "children" : [ ]
        }, {
          "name" : "Email",
          "type" : "java.lang.String",
          "value" : "(781)255-9999^PRN^PH^",
          "children" : [ ]
        }, {
          "name" : "Health_Plan_ID",
          "children" : [ ]
        }, {
          "name" : "Phone_Number_Day",
          "type" : "java.lang.String",
          "value" : "(781)255-9999^PRN^PH^",
          "children" : [ ]
        }, {
          "name" : "PatientAddressRollup",
          "type" : "org.mdmi.core.engine.XDataStruct",
          "value" : {
            "Data Type" : "Address",
            "values" : [ {
              "name" : "city",
              "value" : "NORWOOD"
            }, {
              "name" : "country",
              "value" : "US"
            }, {
              "name" : "county",
              "value" : null
            }, {
              "name" : "nullFlavor",
              "value" : null
            }, {
              "name" : "postalCode",
              "value" : "02062"
            }, {
              "name" : "state",
              "value" : "MA"
            }, {
              "name" : "streetAddressLine",
              "value" : "420 NEPONSET STREET"
            }, {
              "name" : "use",
              "value" : null
            } ]
          },
          "children" : [ ]
        }, {
          "name" : "Phone_Number_Night",
          "type" : "java.lang.String",
          "value" : "(781)255-9999^PRN^PH^",
          "children" : [ ]
        } ]
      }, {
        "name" : "Health_Plan_ID",
        "children" : [ ]
      } ]
    }, {
      "name" : "ACO_MCO_PID",
      "children" : [ ]
    }, {
      "name" : "ACO_MCO_Name",
      "children" : [ ]

[ERROR] NODE/VALUE TYPE MISMATCH CPAssignmentGrouping(781)255-9999^PRN^PH^
[ERROR] NODE/VALUE TYPE MISMATCH
CPAssignmentGrouping/CPAssignmentOrEnrollment(781)255-9999^PRN^PH^
[TRACE] Phone_Number_Cell
[ERROR] NODE/VALUE TYPE MISMATCH
CPAssignmentGrouping/CPAssignmentOrEnrollment(781)255-9999^PRN^PH^
[TRACE] Phone_Number_Night
[ERROR] NODE/VALUE TYPE MISMATCH
CPAssignmentGrouping/CPAssignmentOrEnrollment(781)255-9999^PRN^PH^
[TRACE] Email
[TRACE] Medicaid_ID
[TRACE] Member_Sex
[TRACE] Health_Plan_ID
[ERROR] NODE/VALUE TYPE MISMATCH
CPAssignmentGrouping/CPAssignmentOrEnrollment(781)255-9999^PRN^PH^
[TRACE] Phone_Number_Day

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by mryanlord** [comment]
yep, values in the target semantic and not in the result.xml . also, yep,
I'm not thinking about the roll ups right now. Trying to get the email,
phone, patient ID stuff to come accross.



_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
Is the latest CambridgeMultiples.mdmi in github ?  I see a few issues but not sure if they are just older version - and just to make sure i understand - cambridge is the old partners will multiple documents

**Comment by mryanlord** [comment]
the newest CambridgeMultiples is in github. This is actually a different
msg than Partners. I had some issues with the Partners map I had made, but
I did create a Partners version that works with multples this past week. I
just put that in github.

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
matt
Okay - I pushed a new version in to an "tempFolder" directory 
I think i caused some confusion in the approach here and there was the ui issue of assigning syntax nodes that did not help
If we could push or post the XML that was used to generate the initial map might help 

We have some roll ups and roll downs (and we do no have  roll downs final just yet)
and some adjustments need for the import xml is needed 

We need to identify the "Datatypes" in the xml that needs to not be processed as dataypes
Still need a roll down as well but i want to see the sample xml we are using

**Comment by mryanlord** [comment]
[XML for import.zip](https://github.com/MDMI/mdmiecore/files/2009206/XML.for.import.zip)
I get what you are saying here. Thanks for your help. Find the import xml files attached.

**Comment by swmuir** [comment]
Okay looking at the input xml -i need to add an "ignore" attributes for the sake of matching and consolidating data types;
The issue i was working on is not having multiple Name types when it finds a structure with family name and one that has given - 
in this case the id type and the name type were considered matched leading to the confusion
working on an fix to ignore certain attributes when matching

**Comment by mryanlord** [comment]
Yep. This was the reason I noted the bug/enhancement re: assigning
primitive datatypes to fields in structured datatypes. It seemed to me that
editing these datatypes was important.
Also, althought I agree with all the issues, just want to follow up to ask
if this is reason that I can't get anything from CambridgeMultples as
source to CPassignment2 as target. Thansk Sean

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by mryanlord** [comment]
resolved. datatype import editing necessary.
