### ISSUE TITLE
Add FHIR Period Datatype Mapping

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#137]
Need period datatype to support CDA to FHIR transform for FHIR Procedure Resource Performed element

**Comment by mryanlord** [comment]
Link to fhir standard: https://www.hl7.org/fhir/datatypes.html#period

**Comment by mryanlord** [comment]
Does not seem to be picking up in the model to model transform. FHIR model I'm using for DXC with period mapping in Procedure sent for reference. 
[PeriodDatatypeSupport.zip](https://github.com/MDMI/mdmiecore/files/2128161/PeriodDatatypeSupport.zip)

**Comment by swmuir** [comment]
There is an issue with the period mapping on a choice element - will work on update

**Comment by mryanlord** [comment]
resolved
