### ISSUE TITLE
Error Adding Map from MDMI Conversion Rule

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#147]
Whenever I select "Map from MDMI Conversion Rule" for a semantic element in "DraftC3OutreachMsgMultiples.mdmi" i get this error: "The string resource '_UL_ConversionRule.type' could not be located" (picture below)

![image](https://user-images.githubusercontent.com/19562254/42579048-6d643fc6-84f5-11e8-98bf-94970a6ee86e.png)

**Comment by swmuir** [comment]
Fixed
