### ISSUE TITLE
MDMI Map Editor

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#15]
It does not appear there is a way to edit the high level map stuff such as message model name and default languages (xml, javascript, etc).

**Comment by SallyConway** [comment]
Added sections for Message Group (name, description, Default Rule, Default Location and Default Constraint expression languages) and for Message Model (name, description, source)

**Comment by swmuir** [comment]
Need to recheck

**Comment by KenLord** [comment]
It works now
