### ISSUE TITLE
MST Production Instance: Error returning  valid results from server

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#153]
Logged in as MSTSuperUser
C3.Outreach as source
RiversideUpdate as Target
Using attached pipe delimited .txt file as test message

Local testing in eclipse using XML test message was successful transform. 
[C3UpdateSample.txt](https://github.com/MDMI/mdmiecore/files/2259469/C3UpdateSample.txt)

**Comment by mryanlord** [comment]
Did a pull, stashed a bunch of local changes, but did not get any results
from pull, ie map named C3.Outreach
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
I fixed the online issue - stupid programmer error on defining the deliminator in the runtime 

works now

What i meant was if you do a check for updates you will be able to run the deliminated locally although you need to maps i have as i modified the map slightly to say it is a pipe2xml etc

**Comment by mryanlord** [comment]
yeah, I guessed your check for updates would work with the modified maps,
but they did not come with a pull so I cannot test locally. Can you send
them to me via email? Monday morning I would like to get me back on the
same github page with everyone.

I got the online transform to work, but there are some things getting
dropped. Would like to test locally to get them working. Pls send updated
maps via email.
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
I found an issue with the outbound processing - i made a fix and pushed it out
You should be able to do a restart and check for update to run the update

the online version is updated

**Comment by mryanlord** [comment]
Got an error in eclipse check for updates:

An error occurred while collecting items to be installed
session context
was:(profile=C__Users_mryan_Documents_MDMI_Eclipse_MDMIOxygen-oxygen7_MDMIOxygen,
phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=,
action=).
No repository found containing:
osgi.bundle,org.mdmi.acceleo.module.reports,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.acceleo.module.reports.ui,1.0.0.201808041238
No repository found containing: osgi.bundle,org.mdmi.ant,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.core.runtime,0.5.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.core.runtime.3rdparty,0.0.1.201808041238
No repository found containing:
osgi.bundle,org.mdmi.ecore,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.ecore.edit,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.ecore.editor,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.qvt.blackbox,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.qvt.transforms,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.resource,1.0.0.201808041238
No repository found containing:
osgi.bundle,org.mdmi.uml.ui,1.0.0.201808041238
No repository found containing:
org.eclipse.update.feature,org.mdmi.eclipse,1.0.0.201808041238
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
I was able to run the check for updates 


Try restarting and do check for updates - if the same error

go into help->install new software->whats already installed-

uninstall the mdht and mdmi features and do restart the restart will install the latest

let me know if that does not work

**Comment by mryanlord** [comment]
fixed
