### ISSUE TITLE
FHIM Coverage Report wont' open in Excel

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#16]
XML ERROR in Worksheet Setting
REASON:	Bad Value
FILE:	C:\Users\mryan\eclipse\MDMI-neon\git\maps\FHIM\reports\FHIMFHIMCoverage.xml
GROUP:	Worksheet
TAG:	Table
ATTRIB:	ExpandedRowCount
VALUE:	41000
[FHIMFHIMCoverage.zip](https://github.com/MDMI/mdmiecore/files/976918/FHIMFHIMCoverage.zip)

**Comment by swmuir** [comment]
Fixed
