### ISSUE TITLE
Runtime Exception if MDMI Group Name Identical

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#186]
There two maps threw exception when MDMI Group Name was identical as BHCP
[RuntimeExceptionGroupNameIdentical.zip](https://github.com/MDMI/mdmiecore/files/2318736/RuntimeExceptionGroupNameIdentical.zip)

**Comment by swmuir** [comment]
Fixed

**Comment by mryanlord** [comment]
Gonna take word for it; bug has been intermittent. Will reopen if symptoms reappear
