### ISSUE TITLE
Consol has syntax/naming issues

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#19]
Consol uml has section called FunctionalStatusSection. In this section exists FunctionalStatusResultsOrganizer; there is no such path in CCDA. Maybe related to FunctionalStatusOrganizer, but with bad path/name, etc. Also, FunctionalStatusSection includes CognitiveStatusResultObservation; cognitivestatus is not included in FunctionalStatus in CCDA, not does CognitiveStatus include a ResultObservation.

**Comment by swmuir** [comment]
Need to update the model to the latest

**Comment by KenLord** [comment]
low priority

**Comment by swmuir** [comment]
OBE
