### ISSUE TITLE
CDA "Entries Optional" Sections should Inherit from non-optional sections

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#198]
Certain section templates are optional in different CDA documents. For example, the Encounters section is "Entries Optional" in CCD. There does not seem to be a good reason to do the mapping 2 times; from what I gather the templates are identical, the only difference is if optional.

Don't know if it makes sense to do inheritance or to just have one section. Again, the only difference is in the validation, from what I can tell

**Comment by swmuir** [comment]
The pattern is that required inherits from optional 
We should not map twice but to support inheritance we need to make sure the hierachy is modeled correctly with regard to definisions etc - the easier approach is to change the target of the properties

so if we have mapped a entries required section and document requires an entries optional - change the section definition to use the required section

and vice versa

**Comment by mryanlord** [comment]
Pattern established
