### ISSUE TITLE
FHIR STU 3 Practitioner Resource has container "Role" and child elements

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#208]
This does not exist in the FHIR STU3 spec:
http://hl7.org/fhir/STU3/practitioner.html

**Comment by swmuir** [comment]
STU3 was imported from an update which might have been STU 3.5 I can reimport if that makes things easier

**Comment by mryanlord** [comment]
I looked in all the STU 3.X and didn't see this, which is my concern. I can work around it, but I'd like to resolve this for Perspecta if we get that contract. I looked through earlier versions, and it seems most like DSTU 2 QA (http://hl7.org/fhir/2015Sep/practitioner.html), but the resource model in Eclipse has an "endpoint" element that I don't see in anything. 
FHIR 3.5.0 Practitioner: http://hl7.org/fhir/2018Sep/practitioner.html
FHIR 3.3.0 Practitioner: http://hl7.org/fhir/2018May/practitioner.html
FHIR 3.2.0 Practitioner: http://hl7.org/fhir/2018Jan/practitioner.html
FHIR 3.0.1 Practitioner: http://hl7.org/fhir/STU3/practitioner.html

**Comment by mryanlord** [comment]
Reimported 3.0.1. resolved

**Comment by KenLord** [comment]
we did get the Perspecta Contract
