### ISSUE TITLE
CCD to FHIR code/coding/codeableConcept syntax mix up

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#210]
The runtime is smooshing multiple elements into one syntax going CCD to FHIR Bundle. This does not happen in FHIR ISO. continuityofcaredocument.mdmi and stu4fhirPerspectFHIRmap.mdmi up to date, same with models. Test examples below:

Messed up syntax:

<Condition>
            <identifier>
               <system value="10506b4d-c30a-4220-8bec-97bff9568fd1"/>
            </identifier>
            <category>
               <coding>
                  <code value="75323-6">
                     <coding>
                        <code value="233604007"/>
                        <display value="Pneumonia"/>
                        <system value="2.16.840.1.113883.6.96"/>
                     </coding>
                     <text value="Pneumonia"/>
                  </code>
                  <display value="Condition"/>
                  <system value="2.16.840.1.113883.6.1"/>
               </coding>
               <text value="Condition"/>
            </category>

Correct ISO testing syntax (FHIR side)
<Condition>
            <identifier>
               <system value="ProblemConditionObservationID.system.value"/>
               <value value="ProblemConditionObservationID.value.value"/>
            </identifier>
            <clinicalStatus>
               <coding>
                  <code value="ProblemConditionObservationStatusCode.coding.code.value"/>
                  <display value="ProblemConditionObservationStatusCode.coding.display.value"/>
                  <system value="ProblemConditionObservationStatusCode.coding.system.value"/>
               </coding>
               <text value="ProblemConditionObservationStatusCode.coding.display.value"/>
            </clinicalStatus>
            <verificationStatus>
               <coding>
                  <code value="ProblemConditionObservationVerificationCode.coding.code.value"/>
                  <display value="ProblemConditionObservationVerificationCode.coding.display.value"/>
                  <system value="ProblemConditionObservationVerificationCode.coding.system.value"/>
               </coding>
               <text value="ProblemConditionObservationVerificationCode.coding.display.value"/>
            </verificationStatus>
            <category>
               <coding>
                  <code value="ProblemConditionObservationTypeCode.coding.code.value"/>
                  <display value="ProblemConditionObservationTypeCode.coding.display.value"/>
                  <system value="ProblemConditionObservationTypeCode.coding.system.value"/>
               </coding>
               <text value="ProblemConditionObservationTypeCode.coding.display.value"/>
            </category>
            <code>
               <coding>
                  <code value=""/>
                  <display value="ProblemConditionObservationValueCode.coding.display.value"/>
                  <system value="ProblemConditionObservationValueCode.coding.system.value"/>
               </coding>
               <text value="ProblemConditionObservationValueCode.coding.display.value"/>
            </code>

**Comment by swmuir** [comment]
Can you explain a bit more ?  I am not sure what the issue is?

**Comment by mryanlord** [comment]
Sorry, I thought examples would show. The FHIR problem is this: 
<resource>
         <Condition>
            <identifier>
               <system value="1888c710-a16f-0135-6cb6-60f81dc2d82a"/>
            </identifier>
            <category>
               <coding>
                  <code value="64572001">
                     <coding>
                        <code value="72892002"/>
                        <system value="2.16.840.1.113883.6.96"/>
                     </coding>
                  </code>
                  <display value="Condition"/>
                  <system value="2.16.840.1.113883.6.96"/>
               </coding>
               <text value="Condition"/>
            </category>

**Comment by mryanlord** [comment]
Here is example of .code and .category elements in FHIR Condition resource getting smooshed together
<resource>
         <Condition>
            <identifier>
               <system value="1888c710-a16f-0135-6cb6-60f81dc2d82a"/>
            </identifier>
            <category>
               <coding>
                  <code value="64572001">
                     <coding>
                        <code value="72892002"/>
                        <system value="2.16.840.1.113883.6.96"/>
                     </coding>
                  </code>
                  <display value="Condition"/>
                  <system value="2.16.840.1.113883.6.96"/>
               </coding>
               <text value="Condition"/>
            </category>

**Comment by swmuir** [comment]
the example did not paste correctly for some reason

**Comment by mryanlord** [comment]
fixed
