### ISSUE TITLE
FHIR UML to .mdmi transform creates ContactPoint Datatype Syntax that causes failure

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#212]
The UML to .mdmi transform creates a ContactPoint datatype that has attributes all named correctly, but of 6 attributes, only 1 is leaf node, and the other 5 are incorrectly parse as containers with both .value and .id leaf nodes. Should FHIR_code and FHIR_fhirstring should all be leaf nodes, but are structured datatypes in map. Latest map and model in git.

**Comment by swmuir** [comment]
These seem to all to be correct - in mdmi i did generate them as containers with attributes

examples of a status are

 <status value="generated"/> 

so the status is a container with a leaf attribute 

same for the telecom below - what xml are you attempting to parse ?

<telecom> 
    <system value="phone"/> 
    <value value="(03) 5555 6473"/> 
    <use value="work"/> 
    <rank value="1"/> 
  </telecom>

**Comment by mryanlord** [comment]
Sorry, I'm not doing a good job describing these. Does this picture show up? Can you see how all the identifier attributes are bags, even value, which is supposed to be string (see spec. here: http://hl7.org/fhir/STU3/datatypes.html#Identifier)
![image](https://user-images.githubusercontent.com/19562254/58507395-b16b8280-815f-11e9-811f-27aaeecd4b13.png)

**Comment by mryanlord** [comment]
Nevermind, you are right. Non-issue
