### ISSUE TITLE
Datatype Mapping not Appearing in UML to MDMI Transform

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#225]
Updating maps to do Bulk Transfer and run testing. using FHIRSTU4 FHIR-CoreGenericObs.uml and attached xml for model to model transform (xml renamed to .txt for ease of attachment)

The only datatype mappings that appear in the .mdmi map resulting are StringToX mappings. 

[PerspectaFHIRBulktransformTest.txt](https://github.com/MDMI/mdmiecore/files/3285950/PerspectaFHIRBulktransformTest.txt)

**Comment by swmuir** [comment]
This has to do with changes to the transform ant task
need to add 
	    <path id="workspacePath" location="./model/datatypemappings" />

	    <pathconvert property="datatypemappings" refid="workspacePath"/>

and modify 

<configProperty name="datatypemappings" value="${datatypemappings}" />
				

i will update the transforms in git

**Comment by mryanlord** [comment]
Does it matter where in transform ant task the pathconvert attributes are added?

**Comment by mryanlord** [comment]
never mind last comment, just saw email. thanks

**Comment by mryanlord** [comment]
Resolved, new code for ant transform Identified
