### ISSUE TITLE
Need to pull first 3 characters from ZIP

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#229]
Source example

<PHARMACY_ZIP_3>12345</PHARMACY_ZIP_3>

Target

<Claim>
<subType>
<coding>
<system value="PHARMACY_ZIP_3"/>
<value value="123"/>
</coding>
</subType>
</Claim>

**Comment by swmuir** [comment]
var res = str.substring(0, 3);

**Comment by mryanlord** [comment]
Nope, not a roll up, just a string to Address. Map is ProcedureClaimTable.mdmi is in git.

**Comment by swmuir** [comment]
Buld Data update

**Comment by mryanlord** [comment]
OBE
