### ISSUE TITLE
FHIR_ReferenceToString Datatype Mapping Please

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#232]
Lack of identifiers in Perspecta Bulk data means we need an identifier for Organizations. Will use the Organization Name, which is held as a string. Please add FHIR_ReferenceToString to support this mapping. Thank you.

**Comment by swmuir** [comment]
Should this go into the display of reference ?  that is where hte version i have is

**Comment by swmuir** [comment]
Bulk Data

**Comment by mryanlord** [comment]
function mapStringToFHIR_Reference(source,target) {
 	 target.setValueSafely('display.value', source.getValue());	 
 }
