### ISSUE TITLE
UML to MDMI Scripts for Different C-CDA Documents Not Fully Functional

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#234]
Both transfersummary.xml and dischargesummary.xml leave sections out of the created .mdmi document. Not sure what the issue is. Text versions attached. 
[transfersummary.txt](https://github.com/MDMI/mdmiecore/files/3315880/transfersummary.txt)
[dischargesummary.txt](https://github.com/MDMI/mdmiecore/files/3315892/dischargesummary.txt)

**Comment by swmuir** [comment]
One of two things- i did incorrectly commit a version that was filtering the sections to limit the map 
Also the mappings are not hiearchial  so if the EntriesRequired is mapped and the document had entries optional the mappings will not be found, and vice versa

**Comment by mryanlord** [comment]
user error
