### ISSUE TITLE
Eclipse xml import misread cardinality 

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#25]
[auctiondata3.zip](https://github.com/MDMI/mdmiecore/files/1216178/auctiondata3.zip)
[auctiondata3.zip](https://github.com/MDMI/mdmiecore/files/1216180/auctiondata3.zip)

[auctiondata1.zip](https://github.com/MDMI/mdmiecore/files/1216111/auctiondata1.zip)
[auctiondata1xmi.zip](https://github.com/MDMI/mdmiecore/files/1216113/auctiondata1xmi.zip)
[auctiondata1mdmi.zip](https://github.com/MDMI/mdmiecore/files/1216114/auctiondata1mdmi.zip)

**Comment by swmuir** [comment]
Fixed

**Comment by mryanlord** [comment]
test successful
