### ISSUE TITLE
Reducing Size of MDMI Maps

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#258]
the truvan mdmi map has over 5400 rows in the file. Over 5100 of those rows are for Business Element definitions for each element in the SEER. For performance reasons, we should be required to only have those Business Elements used in the map.  It will probably require changes to the Map generation but it will also probably require some changes to the runtime because not BE will appear in both the source and target.

**Comment by swmuir** [comment]
We have a script to do that

**Comment by KenLord** [comment]
I will follow up to understand later .... thanks
