### ISSUE TITLE
Need to Restart Eclipse on error

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#26]
Imported xml file export_2. 
mdmi file created
error in eclipse when opening the file with "mdmi editor"

when this happens, need to restart eclipse to continue work. 
[export_2 - Copy.docx](https://github.com/MDMI/mdmiecore/files/1216133/export_2.-.Copy.docx)

**Comment by swmuir** [comment]
Duplicate of 24

**Comment by swmuir** [comment]
Duplicate
