### ISSUE TITLE
Eclipse Editor

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#28]
USING A Windows  10 machine,

Bring up mdmi file with Editor, select semantic elements tab, click on a cell in the Business Element column. 

It should provide a dropdown list of possible Business Elements to map to. Nothing happens. If one selects the semantic element in the row, then click on the cell in the Business Element column, then the dropdown list appears. (Same behavior for datatype column).

**Comment by swmuir** [comment]
Could not dup
