### ISSUE TITLE
Editor - changes in table editor not being saved

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#31]
This can be reproduced in any map created.

Select Semantic Element Tab, select a Semantic Element in the table view, select cell in the row in the Business Element Column, in the drop down box select "blank", click to another cell, the "blank" reverts back to the orginal mapping.

(although not necessary, in properties tab, select MDMI general, change Semantic Element Type to Local),

**Comment by swmuir** [comment]
Use Local instead of blank
