### ISSUE TITLE
Lisa Report - some mapped elements not showing up

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#35]
Using map from issue 34, there are mapped elements for the Problem Observation Template.  (id, code, etc.) that are not showing up in the Lisa Report

**Comment by swmuir** [comment]
Ken i need files and specifics - and is it mapped in the MDMI file itself

**Comment by KenLord** [comment]
in Problem Concern Template, it is effectiveTime.
in the Problem Observation Template, it is effectiveTime, Type, Code, Value
in the Age Observation Template, it is Value

Ken

**Comment by swmuir** [comment]
CDA to MDMI, Annotated property not in MDMI Map
Property effective in ProblemConcern.ProblemObservation not in generated MDMI map

**Comment by KenLord** [comment]
[consol2.docx](https://github.com/MDMI/mdmiecore/files/1234504/consol2.docx)

**Comment by KenLord** [comment]
[issue 35.zip](https://github.com/MDMI/mdmiecore/files/1234508/issue.35.zip)

**Comment by KenLord** [comment]
Some mappings of the Semantic Element to the Business Element are not showing up.
the are ProblemConcern.effectiveTime, ProblemConcern.ProblemObservation.effectiveTime, and ProblemConcern.ProblemObservation. code.  

There are also some Semantic elements that show up a mapped in the mdmi map but do not show up in the Lisa Report. The Semantic Elements in the cdamap.mdmi map that do not show up are ProblemConcern.ProblemObservation.value155 and ProblemConcern.ProblemObservation.value150. they are both choice.
