### ISSUE TITLE
Transform options not available in eclipse 

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#42]
drop down has 3 options:
run as
external tool configurations
organize favorites

**Comment by swmuir** [comment]
[MDMILAUNCH.zip](https://github.com/MDMI/mdmiecore/files/1281004/MDMILAUNCH.zip)

**Comment by mryanlord** [comment]
yeah, i figured it out yesterday. Thanks Sean. I closed the ticket

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

Matt Lord
mryanlord@gmail.com

This transmission is intended only for the designated recipient(s). It
contains confidential information that may be subject to the
attorney-client privilege or other confidentiality protections under
applicable law. If you are not a designated recipient, you must not read,
use, copy or distribute this message. If you received this transmission in
error, please notify the sender by telephone (617-930-9305) or by reply
e-mail and delete this message.

**Comment by swmuir** [comment]
Which domain is this not working ?
