### ISSUE TITLE
in Lisa Report, Vital Sign Section Mapping not showing up in report

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#44]
in CCDA mapping,, the section container does not show as mapped in the Lisa Report.  When I open the MDMI file for CDA, it is mapped.

Attached is zip file for CDA
[cda0904.zip](https://github.com/MDMI/mdmiecore/files/1275836/cda0904.zip)

**Comment by swmuir** [comment]
Fixed
