### ISSUE TITLE
.Value grouped with effective time in LISA rpt

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#46]
The value data element for CCDA entries/templates is grouped with the effective time data elements in the LISA report
[effTimeValueLISAs.zip](https://github.com/MDMI/mdmiecore/files/1278873/effTimeValueLISAs.zip)

**Comment by swmuir** [comment]
This is more of formatting issue then a grouping issue - it is not clear from the rows but value is actually under the observation - but effective time is physically before the value and there is no "end of container line/demarcation   - up for suggestions

btw - there is a requirement that the elements be in the physical order of the underlying CDA

**Comment by swmuir** [comment]
If you can figure out a way to make it less confusing i will update the report

**Comment by mryanlord** [comment]
given requirement that elements be in physical order and formatting notes, do not see problem with current formatting. closed
