### ISSUE TITLE
FHIR Mapping Not Showing in LISA rpt with consul source

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#47]
LISA rpt does not show any FHIR mapping whether generated from CDA map or FHIR Map
[Lisa.zip](https://github.com/MDMI/mdmiecore/files/1279119/Lisa.zip)
[resultsLisa.zip](https://github.com/MDMI/mdmiecore/files/1279120/resultsLisa.zip)

**Comment by swmuir** [comment]
Which Domain is not working for

**Comment by mryanlord** [comment]
results

**Comment by swmuir** [comment]
My mapping showed up so after run check for updates rerun the report

**Comment by mryanlord** [comment]
checked, rerun, used 2 different target maps, still no data. 
[Lisa.zip](https://github.com/MDMI/mdmiecore/files/1281997/Lisa.zip)

**Comment by mryanlord** [comment]
OBE
