### ISSUE TITLE
Lisa report generating inaccurate FHIR Path

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#48]
For Lisa Report with CDA as source and FHIR as target and metadata filter is patient info, the Path name and the Datatype for all FHIR mapping is incorrect. Attached are the mdmi files with a .doc extension and I had to zip the file FHIR

[cdamap2.docx](https://github.com/MDMI/mdmiecore/files/1290093/cdamap2.docx)
[fhirccdamapxml2.zip](https://github.com/MDMI/mdmiecore/files/1290095/fhirccdamapxml2.zip)

**Comment by swmuir** [comment]
Fixed
