### ISSUE TITLE
Issue with Path and Datatype in Lisa Report for Patient Info

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#50]
for FHIR  Path, cells contain values such as 
/Bundle/entry/resource/Composition/section/entry/encounter/patient/Bundle/entry/resource/Composition/section/entry/subject/Bundle/entry/resource/Composition/section/entry/encounter/patient/Bundle/entry/resource/Composition/section/entry/subject/Bundle/entry/resource/Composition/extension/value[x]/patient/Bundle/entry/resource/Composition/subject/Bundle/entry/resource/Composition/encounter/patient/Bundle/entry/resource/Composition/encounter/account/coverage/beneficiary/Bundle/entry/resource/Composition/encounter/incomingReferral/patient/Bundle/entry/resource/Composition/encounter/episodeOfCare/patient/Bundle/entry/resource/Co
[cdamap2.docx](https://github.com/MDMI/mdmiecore/files/1290809/cdamap2.docx)

For FHIR Datatypes, cells contain values such as 
FHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_IdentifierFHIR_Identifier

[fhirccdamapxml2.zip](https://github.com/MDMI/mdmiecore/files/1290812/fhirccdamapxml2.zip)

**Comment by swmuir** [comment]
Fixed
