### ISSUE TITLE
the FHIR Data Type in Lisa report is not correct

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#52]
Using the latest version of the software: the FHIR Datatype generated in the LISA report using CDA, FHIR, and Patient Info metadata produces the wrong datatype for the FHIR. For example the FHIR datatype for PatientHomeAddress is

FHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_AddressFHIR_Address

**Comment by swmuir** [comment]
This is a result of the mapping we have on the general patient so we need to not map the general patient structure as it is reused all over the place

**Comment by KenLord** [comment]
Matt,

I am going to re-assign to you.

Ken
