### ISSUE TITLE
CDA to FHIR tranform error

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#59]
Using the attached maps (as docx filetypes) for transforming CDA to FHIR, I get the following error message.
tarting transfer...
2017-10-23 10:01:20 ERROR DatamapInterpreter:157 - Failed executing Executing mapIIToCodedElement := No such function mapIIToCodedElement

Also, can't find a way to copy entire message.
[cdamap - Copy.docx](https://github.com/MDMI/mdmiecore/files/1407417/cdamap.-.Copy.docx)
[fhirccdamapxml - Copy.docx](https://github.com/MDMI/mdmiecore/files/1407421/fhirccdamapxml.-.Copy.docx)

**Comment by swmuir** [comment]
Yes this makes sense because you have a local ID type going to a code type in the SEER
You should have a ID local going to a SEER Codedelement so either the mapping is wrong or the type in the SEER is wrong

**Comment by KenLord** [comment]
Is it possible to isolate the mapping that is causing the error?  Better
yet, can Matt and I do it without bothering you?

**Comment by swmuir** [comment]
The console should have it - right above where you see the error message

**Comment by KenLord** [comment]
I run this in a stand alone test app, I don't run it from eclispe.  Can I
run it from eclispe?

**Comment by swmuir** [comment]
It is semantic element TypeId and syntax node typeId under document root it is an II
you have it mapped to  DocumentTypeCode which is CodedElement

If this in fact is correct we will need to add the datatype map

**Comment by KenLord** [comment]
Implemented decison to change DocumentTypeID to LOCAL and this resolved issue.
