### ISSUE TITLE
Runtime Test app 

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#60]
When saving a generated message in the Runtime test tool, it presently points to the neon version of eclipse to save the file.  Not sure what the correct soluiton is; Configurable, point to Oxygen, etc.

**Comment by swmuir** [comment]
Not sure what you mean - can you post a screen shot

**Comment by KenLord** [comment]
It actually is a series of screen shots and it will be better on a skype
call. It is not a high priority.

**Comment by swmuir** [comment]
OBE - not using the tool anymore

**Comment by KenLord** [comment]
Closed as we are moving to a Web Service Demonstration
