### ISSUE TITLE
MDMID Local semantic element TYPEID is not being properly created

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#63]
TypeID is modeled using custom constraints versus inlined models so the M2M does have a information

**Comment by swmuir** [comment]
Either update consol model to use inline (preferred) or add static to m2m (quicker)

**Comment by swmuir** [comment]
Fixed - addd in to transform as the type id is static across all CDA document instances f

**Comment by KenLord** [comment]
Verified
