### ISSUE TITLE
ANY datatype semantic elements not annotating correctly

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#65]
CDA model includes semantic elements with ANY for datatype
Annotations to SEER elements do not appear in mdmi map
[cdamap.zip](https://github.com/MDMI/mdmiecore/files/1488182/cdamap.zip)

**Comment by swmuir** [comment]
Can you explain further - There are ANY types in CDA - you need to add the .CD or .PQ

**Comment by mryanlord** [comment]
Sean, you put in the fix for this, right?

**Comment by swmuir** [comment]
We currently support two ANY choices (PQ,CD) we can add more as needed

You need to add the corresponding datatype to the map
such as allergyConcernAct2.allergyObservation2.reactionObservation2.severityObservation2.value.CD

The transform logic uses the CDA base class property type (in this case value) to determine how to generate the mdmi syntax node - a choice group

There might be a case were the value attribute definition in the class is not properly redefining the base value property and as such not finding the ANY base type correctly 

Which attribute in which class is not generating a choice in the syntax model ?

**Comment by mryanlord** [comment]
The problem was exactly as you said, "There might be a case were the value attribute definition in the class is not properly redefining the base value property and as such not finding the ANY base type correctly", but I don't see the behavior in the places I previously saw it, so I am going to close this for now, and will reopen if it appears again.
