### ISSUE TITLE
Issues with testing cda iso-morphically

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#67]
[Issues for Matt 11 20.xlsx](https://github.com/MDMI/mdmiecore/files/1488921/Issues.for.Matt.11.20.xlsx)

Sample message is in eclipse project, folder cda/samples/PatientTOC.xml

**Comment by swmuir** [comment]
OBE - ReTest

**Comment by KenLord** [comment]
Tested and executed.
