### ISSUE TITLE
MDHT FHIR Modeling install conflict with MDMI Eclipse Features

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#72]
Tried to update eclipse for new FHIR model transformations and had conflict with MDMI Eclipse features. Uninstalled eclipse features (per install options) and tried to reinstall. Cannot. 
Screenshot of last install try options included.
[FHIReclipseError.zip](https://github.com/MDMI/mdmiecore/files/1521898/FHIReclipseError.zip)

**Comment by swmuir** [comment]
if you go into whats already installed - uninstall all of the MDMI and MDHT features

then do a check for updates 

surprised you are having issues as the last install was okay

if that does not work call my cell 7034473604

**Comment by mryanlord** [comment]
new install complete, issue resolved
