### ISSUE TITLE
Values in target semantic model not written in target FHIR message

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#73]
Significant portions of patient info are in the target semantic model for fhir but not written in message: patient ID, administrative gender, marriage status. Still going through, but hopefully a similar bug for
[12042017.1.zip](https://github.com/MDMI/mdmiecore/files/1527756/12042017.1.zip)
 lots of stuff missing from message output that is in target semantic model.

**Comment by mryanlord** [comment]
Update has new bug. Prior version included patient ID in target semantic model; patient ID no longer in target model. It is in source model. cda, fhir maps attached, as well as messge, and json debug files.
[Issue73dec07.zip](https://github.com/MDMI/mdmiecore/files/1539131/Issue73dec07.zip)

**Comment by swmuir** [comment]
OBE - Update FHIR mapping, transform, and maps
