### ISSUE TITLE
CDA Target Model Values not written to Message

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#75]
Many values not written from Target Model to target message. Examples: Patient ID; Patient Address; Patient Name; Patient Administrative Gender; Patient Marital Status; Patient Religious Affiliation; Patient Telecom

Other syntax issues in target message as well, easily seen in header section 

map, target and source models, message included
[CDAiso12.11.zip](https://github.com/MDMI/mdmiecore/files/1549507/CDAiso12.11.zip)

**Comment by swmuir** [comment]
Fixed Updated transform getAttributes logic
