### ISSUE TITLE
FHIR Inheritances in FHIR CCDA Extensions Model not Appearing in UI

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#76]
Tried mapping the "Resources:Practitioner" inheritances in CCDA-on-FHIR Informant extension, but it does not show in MDMI mapping. 
[FHIRInheritanceMapError.zip](https://github.com/MDMI/mdmiecore/files/1560828/FHIRInheritanceMapError.zip)

**Comment by swmuir** [comment]
Fixed
