### ISSUE TITLE
FHIR Core UML to MDMI Custodian error

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#79]
FHIR Core composition custodian mapping is significantly different from custodian mapping in FHIR mdmi map.
[FHIRumlTOmdmiIssue.zip](https://github.com/MDMI/mdmiecore/files/1564898/FHIRumlTOmdmiIssue.zip)

**Comment by swmuir** [comment]
Fixed - Updated mappings

**Comment by mryanlord** [comment]
annotations in FHIR Core still there, nothing in .mdmi map. Only error on custodian elements is telecom mapping error (reproduced below, probably just needs use conditions), but more than telecom data elements annotated, e.g. DocumentCustodianOrganizationAddress

[qvto:transformation] NEED MAPPING FHIR_ContactPointToDocumentCustodianOrganizationPhoneTelecomMap.js
[qvto:transformation] NEED MAPPING FHIR_ContactPointToDocumentCustodianOrganizationEmailContactTelecomMap.js
[qvto:transformation] NEED MAPPING FHIR_ContactPointToDocumentCustodianOrganizationFaxContactTelecomTelecomMap.js
[qvto:transformation] NEED MAPPING DocumentCustodianOrganizationFaxContactTelecomTelecomToFHIR_ContactPointMap.js
[qvto:transformation] NEED MAPPING FHIR_ContactPointToDocumentCustodianOrganizationPagerContactTelecomTelecomMap.js
[qvto:transformation] NEED MAPPING DocumentCustodianOrganizationPagerContactTelecomTelecomToFHIR_ContactPointMap.js
[qvto:transformation] NEED MAPPING FHIR_ContactPointToDocumentCustodianOrganizationSMSContactTelecomMap.js
[qvto:transformation] NEED MAPPING FHIR_ContactPointToDocumentCustodianOrganizationURLTelecomMap.js

**Comment by mryanlord** [comment]
can't find any mappings current; will remap and test
