### ISSUE TITLE
non-isomorphic mapping

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#8]
used map labelled guardian1. created node, PatientID, type leaf, location PatientIdentifier. Semantic element PatientID, normal, string datatype. Semantic element parent is demographic information. mapping was to ClientID, field, extension. Did isomorphic and non-isomorphic with both append to existing and replace existing, and in all
[guardian1.zip](https://github.com/MDMI/mdmiecore/files/305932/guardian1.zip)

 cases got a dangling ref error

**Comment by mryanlord** [comment]
tried with updates to editor, did same operation above. got to save map, ant build worked fine, BE showed in runtime, but at transformation got an error. Here is it:

![image](https://cloud.githubusercontent.com/assets/19562254/16103348/c7ec8f4c-3345-11e6-84b2-4c088dfeb433.png)

**Comment by swmuir** [comment]
Duplicate
