### ISSUE TITLE
FHIR Problems ISO

### ISSUE THREAD

**Issue by swmuir** [MDMI/mdmiecore#86]
[ERROR] Semantic Element not Transformed ClinicalStatus27
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier661
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code135
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime159
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate28
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category72
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ClinicalStatus29
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier669
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code144
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime165
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate30
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category77
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ClinicalStatus31
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier677
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code153
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime171
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate32
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category82
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ClinicalStatus33
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier685
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code162
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime177
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate34
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category87
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ClinicalStatus37
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier701
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code180
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime189
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate38
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category97
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ClinicalStatus39
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier709
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code189
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime195
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate40
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category102
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ClinicalStatus41
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/clinicalStatus
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed ProblemConditionStatusCode
[ERROR] Semantic Element not Transformed Identifier717
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/identifier
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed ProblemObservationID
[ERROR] Semantic Element not Transformed Code198
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/code
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed ProblemObservationValueCode
[ERROR] Semantic Element not Transformed AbatementdateTime201
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/abatementDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAbateDateTime
[ERROR] Semantic Element not Transformed AssertedDate42
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/assertedDate
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed ProblemObservationAuthorDateTime
[ERROR] Semantic Element not Transformed Category107
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='11450-4']/entry[meta/profile/@value='http://hl7.org/fhir/us/core/structureDefinition/us-core-condition']/category
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Transformed ProblemObservationCategoryCode
[ERROR] Semantic Element not Parsed Section_slice_pos5
[ERROR] Semantic Element not Parsed ClinicalStatus25
[ERROR] Semantic Element not Parsed Identifier653
[ERROR] Semantic Element not Parsed Code126
[ERROR] Semantic Element not Parsed AbatementdateTime153
[ERROR] Semantic Element not Parsed AssertedDate26
[ERROR] Semantic Element not Parsed Category67
[ERROR] Semantic Element not Parsed ClinicalStatus27
[ERROR] Semantic Element not Parsed Identifier661
[ERROR] Semantic Element not Parsed Code135
[ERROR] Semantic Element not Parsed AbatementdateTime159
[ERROR] Semantic Element not Parsed AssertedDate28
[ERROR] Semantic Element not Parsed Category72
[ERROR] Semantic Element not Parsed ClinicalStatus29
[ERROR] Semantic Element not Parsed Identifier669
[ERROR] Semantic Element not Parsed Code144
[ERROR] Semantic Element not Parsed AbatementdateTime165
[ERROR] Semantic Element not Parsed AssertedDate30
[ERROR] Semantic Element not Parsed Category77
[ERROR] Semantic Element not Parsed ClinicalStatus31
[ERROR] Semantic Element not Parsed Identifier677
[ERROR] Semantic Element not Parsed Code153
[ERROR] Semantic Element not Parsed AbatementdateTime171
[ERROR] Semantic Element not Parsed AssertedDate32
[ERROR] Semantic Element not Parsed Category82
[ERROR] Semantic Element not Parsed ClinicalStatus33
[ERROR] Semantic Element not Parsed Identifier685
[ERROR] Semantic Element not Parsed Code162
[ERROR] Semantic Element not Parsed AbatementdateTime177
[ERROR] Semantic Element not Parsed AssertedDate34
[ERROR] Semantic Element not Parsed Category87
[ERROR] Semantic Element not Parsed Section_slice_pos54
[ERROR] Semantic Element not Parsed ClinicalStatus35
[ERROR] Semantic Element not Parsed Identifier693
[ERROR] Semantic Element not Parsed Code171
[ERROR] Semantic Element not Parsed AbatementdateTime183
[ERROR] Semantic Element not Parsed AssertedDate36
[ERROR] Semantic Element not Parsed Category92
[ERROR] Semantic Element not Parsed ClinicalStatus37
[ERROR] Semantic Element not Parsed Identifier701
[ERROR] Semantic Element not Parsed Code180
[ERROR] Semantic Element not Parsed AbatementdateTime189
[ERROR] Semantic Element not Parsed AssertedDate38
[ERROR] Semantic Element not Parsed Category97
[ERROR] Semantic Element not Parsed ClinicalStatus39
[ERROR] Semantic Element not Parsed Identifier709
[ERROR] Semantic Element not Parsed Code189
[ERROR] Semantic Element not Parsed AbatementdateTime195
[ERROR] Semantic Element not Parsed AssertedDate40
[ERROR] Semantic Element not Parsed Category102
[ERROR] Semantic Element not Parsed Identifier717
[ERROR] Semantic Element not Parsed Code198
[ERROR] Semantic Element not Parsed AssertedDate42
[ERROR] Semantic Element not Parsed Category107

**Comment by mryanlord** [comment]
Yeah, this is a nightmare. We should talk about this.

**Comment by mryanlord** [comment]
Simplified. See current error msg below. ProblemObservationValueCode appears in output; so does ProblemObservationID. I have two different BE on Condition ID, would cause below error (do I have to put a container there? Would prefer not.)
Not sure why ProblemSectionNotes error is there, can't find it in annotations or map.

ERROR MSG: 
[INFO] Execute ISOSemantic 
[INFO] Create Source Model 
[INFO] Execute processConversions 
[INFO] Execute processOutboundTargetMessage
[ERROR] Semantic Element not Transformed Text184
[ERROR] Bundle/entry/resource/Composition[meta/profile/@value='http://hl7.org/fhir/ccda/StructureDefinition/CCDA-on-FHIR-Continuity-of-Care-Document']/section[code/coding/code/@value='10160-0']/text
[ERROR] Semantic Element not Transformed ProblemSectionNotes
[ERROR] Semantic Element not Transformed ProblemSectionNotes
[ERROR] Semantic Element not Parsed Text184 (ProblemSectionNotes)
[ERROR] Semantic Element not Parsed Code121 (ProblemObservationValueCode)
[ERROR] Semantic Element not Parsed Identifier678 (ProblemObservationID)
[INFO] Completed Transformation

**Comment by mryanlord** [comment]
works well enough
