### ISSUE TITLE
Testing of CCDA Problems Iso-semantically

### ISSUE THREAD

**Issue by KenLord** [MDMI/mdmiecore#88]
The following issues were identified:
Section
-	No Title
-	No text
-	In code, no CodeSystem Name

Entry Act
-	In code, no CodeSystem Name
-	In Author, need data elements for AuthorID, AuthorCode, AuthorName, Represented Organization: id,name,telecom,address
Entry Relationship – Priority
-	Nit: it should appear below Problem Observation in document
-	No Value

**Comment by mryanlord** [comment]
Something weird going on UML to mdmi; found this in the transform:

[qvto:transformation] NOT USED ProblemConditionAuthorName  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.assignedPerson.name
[qvto:transformation] NOT USED ProblemConditionAuthorSpecialityCode  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.code
[qvto:transformation] NOT USED ProblemConditionAuthorID  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.id
[qvto:transformation] NOT USED ProblemConditionAuthorBusinessAddress  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.representedOrganization.addr
[qvto:transformation] NOT USED ProblemConditionAuthorBusinessPhoneContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemConditionAuthorEmailContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemConditionAuthorFaxContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemConditionAuthorPagerContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemConditionAuthorURLContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemConditionAuthorDateTime  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.authorParticipation.time
[qvto:transformation] NOT USED ProblemObservationAuthorLegalName  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.assignedPerson.name
[qvto:transformation] NOT USED ProblemObservationAuthorSpecialtyCode  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.code
[qvto:transformation] NOT USED ProblemObservationAuthorII  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.id
[qvto:transformation] NOT USED ProblemObservationAuthorOrganizationAddress  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.addr
[qvto:transformation] NOT USED ProblemObservationAuthorOrganizationII  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.id
[qvto:transformation] NOT USED ProblemObservationAuthorOrganizationName  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.name
[qvto:transformation] NOT USED ProblemObservationAuthorEmailContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemObservationAuthorFaxContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemObservationAuthorPagerContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemObservationAuthorSMSContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemObservationAuthorURLContact  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.assignedAuthor.representedOrganization.telecom
[qvto:transformation] NOT USED ProblemObservationAuthorDateTime  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.authorParticipation.time
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorName  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.assignedPerson.name
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorID  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.priorityPreference.authorParticipation.assignedAuthor.id
[qvto:transformation] NOT USED ProblemObservationPriorityAuthorDateTime  ContinuityOfCareDocument2.problemSection2.problemConcernAct2.problemObservation2.priorityPreference.authorParticipation.time

**Comment by swmuir** [comment]
The "NOT USED" is an warning that there are mappings in the model which when walking the model from a generation process were not found - mostly from a path mismatch

**Comment by mryanlord** [comment]
OK, I'll look at the container structure for these elements

**Comment by mryanlord** [comment]
Containers seemed fine. Redid mapping, all the above issues seem resolved

**Comment by mryanlord** [comment]
Sean, can you comment on the above detailed code issues so we can see if we can close this?
