### ISSUE TITLE
CDA Vitals Error Msg and Report Different

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#89]
CDA Vital Sign Isometric testing gave lots of elements not parsed, but they seem to show in the xml generated by the isometric transform. 

Not sure if bug or user error interpreting error msg
[CDAvitalsISO.txt](https://github.com/MDMI/mdmiecore/files/1738102/CDAvitalsISO.txt)
[VitalSigns.txt](https://github.com/MDMI/mdmiecore/files/1738104/VitalSigns.txt)

**Comment by swmuir** [comment]
Fixed

**Comment by mryanlord** [comment]
Checked. Got debugging instructions for CDA. Checked on FHIR, which has variant. If mapping US Core and using FHIR Core inheritance, cannot set Redefine.
