### ISSUE TITLE
no format button in new editor

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#9]
no format button in new editor

**Comment by KenLord** [comment]
Sally, when the syntax model is selected in the table view, and properties/MDMI General is selected in the lower left window, there is no way to set the format for a dateTime LTS node (either field or attribute). The format for a dateTime LTS node must be specified or else the runtime throws an error. 

Need to ability to enter a format for an LTS node.

**Comment by swmuir** [comment]
Missing Data field format in UI

**Comment by swmuir** [comment]
Date time formatting is supported through Datatype mapping but not through the syntax mode- this needs to be supported as part of update to datatype
