### ISSUE TITLE
Telecom Limited to 1 instance in CDA General Header

### ISSUE THREAD

**Issue by mryanlord** [MDMI/mdmiecore#98]
Has multiple cardinality on model
has multiple seer elements mapped, with conditions

example

 <recordTarget>
        <patientRole>
            <id
                assigningAuthorityName="PatientID.assigningAuthorityName"
                displayable="PatientID.displayable"
                extension="PatientID.extension" root="PatientID.root"/>
            <addr>
                <postalCode>PatientAddress.postalCode</postalCode>
                <country>PatientAddress.country</country>
                <state>PatientAddress.state</state>
                <city>PatientAddress.city</city>
                <streetAddressLine>PatientAddress.streetAddressLine</streetAddressLine>
            </addr>
            <telecom use="home" value="PatientEmailContact.value"/>

**Comment by swmuir** [comment]
The telecom in the mdmi model is set to 1 to many so i am not sure what the issue is here

**Comment by mryanlord** [comment]
sorry poorly written:

there is only 1 telecom appearing in general header during transform, even if more in message. probably related to issue #93

**Comment by swmuir** [comment]
Fixed
